version: '3'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports: 
      - "5433:5432"

  redis:
    image: redis:6.2-alpine

  # cron:
  #   build: .
  #   command: ["python", "cron_job.py"]  # todo: edit path later
  #   env_file:
  #     - .env
  #   depends_on:
  #     - db
  #     - redis

volumes:
  postgres_data:
