name: Python package

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install autoflake black isort pylint pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with autoflake black isort pylint
      run: |
        autoflake src -r --remove-all-unused-imports --remove-duplicate-keys --remove-unused-variables --in-place --recursive
        black src
        isort src
        pylint --extension-pkg-whitelist='pydantic' src
    # - name: Test with pytest
    #   run: |
    #     pytest
